### ISSUE TITLE
Diviz

### ISSUE THREAD

**Issue by kkakama** [kkakama/J-XMCDA#1]
binome :  Sandra Tuza Mangara et Kakama SALL 
complexité 1

**Comment by kkakama** [comment]
Le rapport sur cette issue concernant le logiciel Diviz se trouve dans la branche "DivizIssue"

**Comment by oliviercailloux** [comment]
Travail bien effectué. Problèmes de mise en forme à résoudre. Voir https://github.com/kkakama/J-XMCDA/blob/DivizIssue/RapportDiviz.adoc.
