### ISSUE TITLE
ServiceDescr

### ISSUE THREAD

**Issue by kkakama** [kkakama/J-XMCDA#4]
Binome : Kakama SALL et Sami Meskaoui

Objet WebServiceDescription : un ensemble de paires d’id (string) et de type (un type au sens XML). Les types sont ceux qui peuvent servir de type de base dans le schéma xmcda-modular, plus un type spécial représentant le type de base X2. Ce dernier nous servira de type par défaut, car il est très général. Encodage et décodage de l’objet WebServiceDescription en JSON. (1)

**Comment by oliviercailloux** [comment]
Objet WebServiceDescription: ne doit pas contenir un id et un type (qui représentent une paire) mais bien un ensemble de paires. Cet ensemble de paires doit appartenir à l’instance et non être commun à toutes les instances, ce qui est pour le moment le cas puisque la Map est "static".
Les valeurs pour enum XmcdaMdoularTypes devraient être en majuscules (par convention) car ce sont des constantes. Inutile d’ajouter des accolades vides. Fonction toString inutile. Le nom devrait être XmcdaModularType, car c’est ce que représente une instance.

JSON: voir BP exceptions. Utiliser try with resources. (Voir JSON dans cours.) Possible de simplifier le code, utiliser l’API Object Model et non Streaming. Pour l’encodage, ne pas écrire directement dans un fichier mais donner la possibilité à l’appelant d’utiliser le résultat intermédiaire, ce qui rend le code plus général. Tests attendus.
